title: Settler Environments
description: Uncovering and exploring Australian and New Zealand settler poetry as a form of environmental knowledge.
theme: jekyll-theme-cayman
site_favicon: Settler_Environments-Secondary-Logo-Black-RGB.eps
